--- tools/testing/selftests/Makefile
+++ tools/testing/selftests/Makefile
@@ -4,6 +4,7 @@
 TARGETS += kcmp
 TARGETS += memory-hotplug
 TARGETS += mqueue
+TARGETS += mount
 TARGETS += net
 TARGETS += ptrace
 TARGETS += vm
